---
- hosts: localhost
  tasks:
    - name: install git
      yum:
        name: git
        state: present
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: start httpd service
      service:
        name: httpd
        state: started
